const express=require('express');
const cors=require('cors');
const WebSocket=require('ws');
const app=express(); app.use(cors()); app.use(express.static('public'));
const PORT=process.env.PORT||3000,ORIGIN='https://www.formula1.com',HTTP='https://livetiming.formula1.com/signalrcore',WS='wss://livetiming.formula1.com/signalrcore',STATIC='https://livetiming.formula1.com/static/',YEAR=2026,RS='\x1e';
const CHANNELS=['TimingData','TimingDataF1','TimingAppData','DriverList','SessionInfo','SessionStatus','ExtrapolatedClock','WeatherData','RaceControlMessages','LapCount','TrackStatus'];
const state={connected:false,lastMessageAt:null,lastTimingAt:null,timing:{Lines:{}},app:{Lines:{}},drivers:{},session:{},sessionStatus:{},clock:{},weather:{},lap:{},track:{},raceControl:[]};
const archiveCache=new Map();
function plain(x){return x&&typeof x==='object'&&!Array.isArray(x)}
function merge(a,b){if(!plain(a)||!plain(b))return b===undefined?a:b;for(const k of Object.keys(b)){const v=b[k];if(v===undefined)continue;if(plain(v)){if(!plain(a[k]))a[k]={};merge(a[k],v)}else if(Array.isArray(v))a[k]=v.slice();else a[k]=v}return a}
function route(ch,payload){if(payload==null)return;if(ch==='TimingData'||ch==='TimingDataF1')state.lastTimingAt=new Date().toISOString();const d=typeof payload==='string'?JSON.parse(payload):payload;if(ch==='TimingData'||ch==='TimingDataF1')merge(state.timing,d);else if(ch==='TimingAppData')merge(state.app,d);else if(ch==='DriverList')merge(state.drivers,d);else if(ch==='SessionInfo')merge(state.session,d);else if(ch==='SessionStatus'){if(plain(d))merge(state.sessionStatus,d);else state.sessionStatus={Status:String(d)}}else if(ch==='ExtrapolatedClock')merge(state.clock,d);else if(ch==='WeatherData')merge(state.weather,d);else if(ch==='LapCount')merge(state.lap,d);else if(ch==='TrackStatus')merge(state.track,d);else if(ch==='RaceControlMessages'&&d.Messages){const m=(Array.isArray(d.Messages)?d.Messages:Object.values(d.Messages)).filter(plain);state.raceControl=[...state.raceControl,...m].slice(-100)}}
function snapshot(result){for(const ch of CHANNELS)if(result?.[ch]!=null)route(ch,result[ch])}
async function connect(){try{const pre=await fetch(HTTP+'/negotiate',{method:'OPTIONS',headers:{'User-Agent':'BestHTTP',Origin:ORIGIN}});const cookie=(pre.headers.get('set-cookie')||'').match(/AWSALBCORS=([^;]+)/)?.[1]||'';const headers={'User-Agent':'BestHTTP',Origin:ORIGIN,'Content-Type':'text/plain'};if(cookie)headers.Cookie='AWSALBCORS='+cookie;const n=await fetch(HTTP+'/negotiate?negotiateVersion=1',{method:'POST',headers});if(!n.ok)throw Error('Negotiate HTTP '+n.status);const j=await n.json(),wh={'User-Agent':'BestHTTP',Origin:ORIGIN};if(cookie)wh.Cookie='AWSALBCORS='+cookie;const ws=new WebSocket(WS+'?id='+encodeURIComponent(j.connectionToken),{headers:wh});let handshake=false;ws.on('open',()=>ws.send('{"protocol":"json","version":1}'+RS));ws.on('message',buf=>{state.lastMessageAt=new Date().toISOString();for(const seg of buf.toString('utf8').split(RS)){if(!seg)continue;try{const f=JSON.parse(seg);if(!handshake){if(f.error)throw Error(f.error);handshake=true;state.connected=true;ws.send(JSON.stringify({type:1,invocationId:'0',target:'Subscribe',arguments:[CHANNELS]})+RS);continue}if(f.type===3&&f.invocationId==='0'&&f.result)snapshot(f.result);if(f.type===1&&f.target==='feed'&&f.arguments?.length>=2)route(f.arguments[0],f.arguments[1])}catch(e){}}});ws.on('close',()=>{state.connected=false;setTimeout(connect,5000)});ws.on('error',()=>{})}catch(e){state.connected=false;setTimeout(connect,5000)}}
connect();
function currentStint(x){const st=x?.Stints;if(!st)return null;const a=(Array.isArray(st)?st:Object.values(st)).filter(plain);return a.length?a[a.length-1]:null}
function makeRows(drivers,timing,appData){const lines=timing?.Lines||{},apps=appData?.Lines||{};const nums=new Set([...Object.keys(drivers||{}),...Object.keys(lines),...Object.keys(apps)]);return [...nums].filter(n=>n&&!String(n).startsWith('_')).map(n=>{const d=drivers?.[n]||{},t=lines[n]||{},a=apps[n]||{},st=currentStint(a);return{number:n,position:Number(t.Position||a.Position||999),tla:d.Tla||n,name:d.FullName||d.BroadcastName||'',team:d.TeamName||'',teamColour:d.TeamColour||'777777',gap:t.GapToLeader?.Value||t.GapToLeader||'',interval:t.IntervalToPositionAhead?.Value||t.IntervalToPositionAhead||'',lastLap:t.LastLapTime?.Value||'',bestLap:t.BestLapTime?.Value||'',inPit:!!t.InPit,pitOut:!!t.PitOut,pitStops:t.NumberOfPitStops??null,retired:!!t.Retired,stopped:!!t.Stopped,compound:st?.Compound||'',tyreLaps:st?.TotalLaps??st?.StartLaps??null}}).sort((a,b)=>a.position-b.position)}
function rows(){return makeRows(state.drivers,state.timing,state.app)}
function sessionStatusValue(){return state.sessionStatus?.Status||state.sessionStatus?.SessionStatus||state.session?.SessionStatus||''}
function feedStatus(){if(!state.connected)return'OFFLINE';const ss=String(sessionStatusValue()).toLowerCase(),archive=String(state.session?.ArchiveStatus?.Status||'').toLowerCase();if(['finalised','finished','ended'].includes(ss)||archive==='complete')return'FINAL';if(['started','active','running'].includes(ss)){if(!state.lastTimingAt)return'CONNECTING';return Date.now()-Date.parse(state.lastTimingAt)<=30000?'LIVE':'STALE'}return rows().length?'STALE':'WAITING'}
function safePath(p){return typeof p==='string'&&p.startsWith(String(YEAR)+'/')&&/^[\w\-./]+$/.test(p)&&!p.includes('..')}
async function fetchArchive(rel,ttl=300000){const now=Date.now(),hit=archiveCache.get(rel);if(hit&&now-hit.at<ttl)return hit.data;const r=await fetch(STATIC+rel,{headers:{'User-Agent':'BestHTTP',Origin:ORIGIN,Referer:ORIGIN+'/',Accept:'application/json,text/plain,*/*'}});if(!r.ok)throw Error('Archive HTTP '+r.status+' '+rel);const txt=(await r.text()).replace(/^\uFEFF/,'');const data=JSON.parse(txt);archiveCache.set(rel,{at:now,data});return data}
async function seasonIndex(){return fetchArchive(YEAR+'/Index.json',120000)}
function sessionSortKey(s){const t=Date.parse(s.StartDate||s.EndDate||'');if(Number.isFinite(t))return t;const m=String(s.Path||'').match(/(\d{4}-\d{2}-\d{2})/);return m?Date.parse(m[1]+'T00:00:00Z'):0}
function flattenSessions(idx){const out=[];for(const meeting of idx?.Meetings||[])for(const s of meeting.Sessions||[])if(safePath(s.Path))out.push({...s,meeting:{Key:meeting.Key,Name:meeting.Name,OfficialName:meeting.OfficialName,Location:meeting.Location,Country:meeting.Country,Circuit:meeting.Circuit}});return out.sort((a,b)=>sessionSortKey(a)-sessionSortKey(b))}
async function getTopic(path,topic){if(!safePath(path))throw Error('Bad archive path');const idx=await fetchArchive(path+'Index.json',300000),feed=idx?.Feeds?.[topic],kp=feed?.KeyFramePath;if(!kp)return null;return fetchArchive(path+kp,300000)}
async function buildArchiveSession(path,meta=null){const topics=['SessionInfo','TimingData','TimingAppData','DriverList','WeatherData','RaceControlMessages','LapCount','TrackStatus','ExtrapolatedClock'];const vals=await Promise.all(topics.map(t=>getTopic(path,t).catch(()=>null)));const [session,timing,appData,drivers,weather,raceControl,lap,track,clock]=vals;const messages=raceControl?.Messages?(Array.isArray(raceControl.Messages)?raceControl.Messages:Object.values(raceControl.Messages)).filter(plain):[];return{version:'0.6.0',source:'archive',live:false,status:'RESULT',connected:state.connected,archivePath:path,lastMessageAt:state.lastMessageAt,lastTimingAt:null,session:session||{Name:meta?.Name||meta?.Type||'Session',Meeting:meta?.meeting||{}},sessionStatus:'Finalised',clock:clock||{},lap:lap||{},track:track||{},weather:weather||{},drivers:makeRows(drivers||{},timing||{},appData||{}),raceControl:messages.slice(-20).reverse()}}
app.get('/api/live',(req,res)=>{const status=feedStatus();res.json({version:'0.6.0',source:'live',live:status==='LIVE',status,connected:state.connected,lastMessageAt:state.lastMessageAt,lastTimingAt:state.lastTimingAt,session:state.session,sessionStatus:sessionStatusValue(),clock:state.clock,lap:state.lap,track:state.track,weather:state.weather,drivers:rows(),raceControl:state.raceControl.slice(-20).reverse()})});
app.get('/api/archive/meetings',async(req,res)=>{try{const idx=await seasonIndex();const meetings=(idx?.Meetings||[]).map(m=>({Key:m.Key,Name:m.Name,OfficialName:m.OfficialName,Location:m.Location,Country:m.Country,Circuit:m.Circuit,Sessions:(m.Sessions||[]).filter(s=>safePath(s.Path)).map(s=>({Key:s.Key,Name:s.Name,Type:s.Type,StartDate:s.StartDate,EndDate:s.EndDate,Path:s.Path}))}));res.json({version:'0.6.0',year:YEAR,meetings})}catch(e){res.status(502).json({error:String(e.message||e)})}});
app.get('/api/archive/latest',async(req,res)=>{try{const sessions=flattenSessions(await seasonIndex());if(!sessions.length)return res.status(404).json({error:'No archived sessions'});const s=sessions[sessions.length-1];res.json(await buildArchiveSession(s.Path,s))}catch(e){res.status(502).json({error:String(e.message||e)})}});
app.get('/api/archive/session',async(req,res)=>{try{const path=String(req.query.path||'');if(!safePath(path))return res.status(400).json({error:'Invalid path'});res.json(await buildArchiveSession(path))}catch(e){res.status(502).json({error:String(e.message||e)})}});
app.get('/api/status',(req,res)=>res.json({version:'0.6.0',connected:state.connected,status:feedStatus(),lastMessageAt:state.lastMessageAt,lastTimingAt:state.lastTimingAt,sessionStatus:sessionStatusValue()||null,drivers:rows().length}));
app.listen(PORT,()=>console.log('Paddock Pulse Live V0.6 http://localhost:'+PORT));
